package Persistent;


/**
* Persistent/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersistentHello.idl
* Sunday, August 27, 2017 12:29:10 PM VET
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
